package daemon

import (
	"errors"
	"regexp"

	"github.com/sagernet/sing-box/protocol/pokrov/localdpi"
	"github.com/sagernet/sing-box/protocol/pokrov/smartaccess"
)

var routingCatalogServiceID = regexp.MustCompile(`^[a-z0-9][a-z0-9._-]{0,63}$`)

func (s *StartedService) ReadLocalDpiAdmissionID(outboundTag string) (string, error) {
	s.serviceAccess.RLock()
	defer s.serviceAccess.RUnlock()
	if s.closed || s.serviceStatus.Status != ServiceStatus_STARTED || s.instance == nil {
		return "", errors.New("local_dpi_runtime_unavailable")
	}
	for _, outbound := range s.instance.instance.Outbound().Outbounds() {
		if local, ok := outbound.(*localdpi.Outbound); ok && local.Tag() == outboundTag {
			return local.AdmissionID(), nil
		}
	}
	return "", errors.New("local_dpi_admission_unavailable")
}

// A native proof can admit only the exact holder it read from this runtime.
// The ID is generated by Core and changes even on a same-profile reload.
func (s *StartedService) AdmitLocalDpiAdmission(admissionID string) (bool, error) {
	s.serviceAccess.RLock()
	defer s.serviceAccess.RUnlock()
	if s.closed || s.serviceStatus.Status != ServiceStatus_STARTED || s.instance == nil {
		return false, errors.New("local_dpi_runtime_unavailable")
	}
	for _, outbound := range s.instance.instance.Outbound().Outbounds() {
		if local, ok := outbound.(*localdpi.Outbound); ok && local.AdmissionID() == admissionID {
			return local.AdmitAdmission(admissionID), nil
		}
	}
	return false, nil
}

// This only closes one admission latch. Internal flow observers change their
// captured holder directly so shutdown never re-enters serviceAccess.
func (s *StartedService) WithdrawLocalDpiAdmission(admissionID string) (bool, error) {
	s.serviceAccess.RLock()
	defer s.serviceAccess.RUnlock()
	if s.closed || s.serviceStatus.Status != ServiceStatus_STARTED || s.instance == nil {
		return false, errors.New("local_dpi_runtime_unavailable")
	}
	for _, outbound := range s.instance.instance.Outbound().Outbounds() {
		if local, ok := outbound.(*localdpi.Outbound); ok && local.AdmissionID() == admissionID {
			return local.WithdrawAdmission(admissionID), nil
		}
	}
	return false, nil
}

func (s *StartedService) RevokeRoutingCatalogService(serviceID string) (bool, error) {
	if !routingCatalogServiceID.MatchString(serviceID) { return false, errors.New("catalog_service_invalid") }
	s.serviceAccess.RLock()
	defer s.serviceAccess.RUnlock()
	if s.closed || s.serviceStatus.Status != ServiceStatus_STARTED || s.instance == nil {
		return false, errors.New("catalog_runtime_unavailable")
	}
	return s.instance.instance.RevokeRoutingCatalogService(serviceID), nil
}

// A whole-catalog withdrawal closes leased provider flows as well as removing
// catalog rule admission. It is not a transport-error or refresh-expiry action.
func (s *StartedService) RevokeRoutingCatalog() (bool, error) {
	s.serviceAccess.RLock()
	defer s.serviceAccess.RUnlock()
	if s.closed || s.serviceStatus.Status != ServiceStatus_STARTED || s.instance == nil {
		return false, errors.New("catalog_runtime_unavailable")
	}
	instance := s.instance.instance
	found := instance.RevokeRoutingCatalog()
	for _, outbound := range instance.Outbound().Outbounds() {
		if lease, ok := outbound.(*smartaccess.Outbound); ok {
			lease.Revoke(true)
			found = true
		}
	}
	return found, nil
}
