package daemon

import (
	"encoding/json"
	"errors"
	"regexp"

	"github.com/sagernet/sing-box/protocol/pokrov/localdpi"
	"github.com/sagernet/sing-box/protocol/pokrov/smartaccess"
	"github.com/sagernet/sing-box/protocol/pokrov/telegramws"
)

var routingCatalogServiceID = regexp.MustCompile(`^[a-z0-9][a-z0-9._-]{0,63}$`)

func (s *StartedService) ReadLocalDpiAdmissionID(outboundTag string) (string, error) {
	s.serviceAccess.RLock()
	defer s.serviceAccess.RUnlock()
	if s.closed || s.serviceStatus.Status != ServiceStatus_STARTED || s.instance == nil {
		return "", errors.New("local_dpi_runtime_unavailable")
	}
	for _, outbound := range s.instance.instance.Outbound().Outbounds() {
		if local, ok := outbound.(*localdpi.Outbound); ok && local.Tag() == outboundTag {
			return local.AdmissionID(), nil
		}
	}
	return "", errors.New("local_dpi_admission_unavailable")
}

// Observation is scoped to the current captured holder, including after its
// withdrawal. A same-profile successor has a new ID and cannot supply this read.
func (s *StartedService) ReadLocalDpiObservation(admissionID string) (string, error) {
	s.serviceAccess.RLock()
	defer s.serviceAccess.RUnlock()
	if s.closed || s.serviceStatus.Status != ServiceStatus_STARTED || s.instance == nil {
		return "", errors.New("local_dpi_runtime_unavailable")
	}
	for _, outbound := range s.instance.instance.Outbound().Outbounds() {
		if local, ok := outbound.(*localdpi.Outbound); ok && local.AdmissionID() == admissionID {
			encoded, err := json.Marshal(local.ReadObservation())
			return string(encoded), err
		}
	}
	return "", nil
}

// A native proof can admit only the exact holder it read from this runtime.
// The ID is generated by Core and changes even on a same-profile reload.
func (s *StartedService) AdmitLocalDpiAdmission(admissionID string) (bool, error) {
	s.serviceAccess.RLock()
	defer s.serviceAccess.RUnlock()
	if s.closed || s.serviceStatus.Status != ServiceStatus_STARTED || s.instance == nil {
		return false, errors.New("local_dpi_runtime_unavailable")
	}
	for _, outbound := range s.instance.instance.Outbound().Outbounds() {
		if local, ok := outbound.(*localdpi.Outbound); ok && local.AdmissionID() == admissionID {
			return local.AdmitAdmission(admissionID), nil
		}
	}
	return false, nil
}

// This only closes one admission latch. Internal flow observers change their
// captured holder directly so shutdown never re-enters serviceAccess.
func (s *StartedService) WithdrawLocalDpiAdmission(admissionID string) (bool, error) {
	s.serviceAccess.RLock()
	defer s.serviceAccess.RUnlock()
	if s.closed || s.serviceStatus.Status != ServiceStatus_STARTED || s.instance == nil {
		return false, errors.New("local_dpi_runtime_unavailable")
	}
	for _, outbound := range s.instance.instance.Outbound().Outbounds() {
		if local, ok := outbound.(*localdpi.Outbound); ok && local.AdmissionID() == admissionID {
			return local.WithdrawAdmission(admissionID), nil
		}
	}
	return false, nil
}

func (s *StartedService) RevokeRoutingCatalogService(serviceID string) (bool, error) {
	if !routingCatalogServiceID.MatchString(serviceID) {
		return false, errors.New("catalog_service_invalid")
	}
	s.serviceAccess.RLock()
	defer s.serviceAccess.RUnlock()
	if s.closed || s.serviceStatus.Status != ServiceStatus_STARTED || s.instance == nil {
		return false, errors.New("catalog_runtime_unavailable")
	}
	instance := s.instance.instance
	found := false
	for _, outbound := range instance.Outbound().Outbounds() {
		if tg, ok := outbound.(*telegramws.Outbound); ok && tg.ServiceID() == serviceID {
			found = tg.WithdrawAdmission(tg.AdmissionID()) || found
		}
	}
	return instance.RevokeRoutingCatalogService(serviceID) || found, nil
}

// A whole-catalog withdrawal closes leased provider flows as well as removing
// catalog rule admission. It is not a transport-error or refresh-expiry action.
func (s *StartedService) RevokeRoutingCatalog() (bool, error) {
	s.serviceAccess.RLock()
	defer s.serviceAccess.RUnlock()
	if s.closed || s.serviceStatus.Status != ServiceStatus_STARTED || s.instance == nil {
		return false, errors.New("catalog_runtime_unavailable")
	}
	instance := s.instance.instance
	found := false
	for _, outbound := range instance.Outbound().Outbounds() {
		if tg, ok := outbound.(*telegramws.Outbound); ok {
			found = tg.WithdrawAdmission(tg.AdmissionID()) || found
		}
	}
	found = instance.RevokeRoutingCatalog() || found
	for _, outbound := range instance.Outbound().Outbounds() {
		if lease, ok := outbound.(*smartaccess.Outbound); ok {
			lease.Revoke(true)
			found = true
		}
	}
	return found, nil
}

func (s *StartedService) ReadTelegramWSAdmissionID(outboundTag string) (string, error) {
	s.serviceAccess.RLock()
	defer s.serviceAccess.RUnlock()
	if s.closed || s.serviceStatus.Status != ServiceStatus_STARTED || s.instance == nil {
		return "", errors.New("telegram_ws_runtime_unavailable")
	}
	for _, outbound := range s.instance.instance.Outbound().Outbounds() {
		if tg, ok := outbound.(*telegramws.Outbound); ok && tg.Tag() == outboundTag {
			return tg.AdmissionID(), nil
		}
	}
	return "", errors.New("telegram_ws_admission_unavailable")
}

func (s *StartedService) AdmitTelegramWSAdmission(id string) (bool, error) {
	s.serviceAccess.RLock()
	defer s.serviceAccess.RUnlock()
	if s.closed || s.serviceStatus.Status != ServiceStatus_STARTED || s.instance == nil {
		return false, errors.New("telegram_ws_runtime_unavailable")
	}
	for _, outbound := range s.instance.instance.Outbound().Outbounds() {
		if tg, ok := outbound.(*telegramws.Outbound); ok && tg.AdmissionID() == id {
			return tg.AdmitAdmission(id), nil
		}
	}
	return false, nil
}

func (s *StartedService) WithdrawTelegramWSAdmission(id string) (bool, error) {
	s.serviceAccess.RLock()
	defer s.serviceAccess.RUnlock()
	if s.closed || s.serviceStatus.Status != ServiceStatus_STARTED || s.instance == nil {
		return false, errors.New("telegram_ws_runtime_unavailable")
	}
	for _, outbound := range s.instance.instance.Outbound().Outbounds() {
		if tg, ok := outbound.(*telegramws.Outbound); ok && tg.AdmissionID() == id {
			return tg.WithdrawAdmission(id), nil
		}
	}
	return false, nil
}
